;
; File generated by cc65 v 2.18 - Git 24c8e3f
;
	.fopt		compiler,"cc65 v 2.18 - Git 24c8e3f"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_g_text
	.export		_g_blank_text
	.export		_g_palettes
	.export		_g_attributes
	.export		_g_i
	.export		_g_j
	.export		_g_attr_offset
	.export		_g_state
	.export		_g_sprites

.segment	"DATA"

_g_state:
	.word	$0001

.segment	"RODATA"

_g_text:
	.byte	$50,$72,$65,$73,$73,$20,$53,$74,$61,$72,$74,$21,$21,$00
_g_blank_text:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$00
_g_palettes:
	.byte	$0F
	.byte	$12
	.byte	$20
	.byte	$16
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$28
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$0F
	.byte	$12
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_g_attributes:
	.byte	$00
	.byte	$90
	.byte	$40
	.byte	$E0
	.byte	$80
	.byte	$40
	.byte	$20
	.byte	$D0
	.byte	$40
	.byte	$20
	.byte	$90
	.byte	$C0

.segment	"BSS"

.segment	"ZEROPAGE"
_g_i:
	.res	1,$00
_g_j:
	.res	1,$00
_g_attr_offset:
	.res	1,$00
.segment	"OAM"
_g_sprites:
	.res	256,$00

